# Generated by Django 5.1.1 on 2024-11-05 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj_sprava', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='horse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='staj_sprava.horse'),
        ),
    ]
