# Generated by Django 5.1.1 on 2024-11-11 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj_sprava', '0002_alter_training_horse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='care',
            name='horse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_sessions', to='staj_sprava.horse'),
        ),
    ]
